### ISSUE TITLE
Can’t host dolos web app publicly

### ISSUE THREAD

**Issue by fatenocaster** [dodona-edu/dolos#1439]
**Describe the bug**
cant host dolos web app publicly

**To Reproduce**
1. modify docker-compose.yml as follows:
```
environment:
      VITE_HOST: 0.0.0.0
      VITE_PORT: 8080
      #VITE_API_URL: http://localhost:3000
      VITE_API_URL: http://192.168.111.200:3000
      VITE_MODE: server
```
change VITE_API_URL to http://192.168.111.200:3000(my public ip)

2. delete original web image :
sudo docker image rm dolos-web

3. rebuild and start docker containers
suo docker-compose up -d

**Expected behavior**
upload code samples but still redirect to localhost:3000
