### ISSUE TITLE
Self hosting Dolos using docker-compose

### ISSUE THREAD

**Issue by mikaelGusse** [dodona-edu/dolos#1518]
**Which component(s) is your question about?**
Self-hosting Dolos web app

**What is your question?**
Hello! We here at Aalto are having some difficulties hosting Dolos on our own servers at the moment. We are trying to use the docker-compose method to host it. We are using nginx as well for this setup. Currently we are able to open up the web front end and submit a file for analysis. It manages to complete the analysis succesfully (most of the time) but when we try to open up the report it tries to fetch the report from the wrong place for some reason. Instead of going through https://DOLOS_URL/api/reports it tries to get the report from http://DOLOS_URL/reports. This happens despite us settings the VITE_API_URL to the https. 

Our current nginx.conf looks like this:
```
events {}

http {

    upstream dolos-api {
        server api:3000;
    }

    upstream dolos-web {
        server web:8080;
    }

    server {
        listen 80;
        server_name {INSERT DOLOS URL HERE};

        location / {
            return 301 https://$host$request_uri;
        }
    }

    server {
        listen 443 ssl;
        server_name {INSERT DOLOS URL HERE};

        ssl_certificate /etc/ssl/private/fullchain.pem;
        ssl_certificate_key /etc/ssl/private/privkey.pem;

        location /{
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Host $host;
            proxy_pass http://dolos-web/;
        }

        location /api {
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Host $host;
            proxy_pass http://dolos-api/;
        }
    }
}

```

And our current docker-compose looks like this

```
name: dolos
version: "3.9"
services:
  db:
    image: mariadb:11
    volumes:
      - dolos-db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: {INSERT PASSWORD HERE}
    networks:
      - dolos
    healthcheck:
      start_period: 2s
      interval: 5s
      test: healthcheck.sh --su-mysql --connect --innodb_initialized
  web:
    image: ghcr.io/dodona-edu/dolos-web
    build: ./web/
    environment:
      VITE_HOST: 0.0.0.0
      VITE_PORT: 8080
      VITE_API_URL: https://{INSERT DOLOS URL HERE}/api
      VITE_MODE: server
    depends_on:
      - api
    networks:
      - dolos
    healthcheck:
      start_period: 2s
      interval: 5s
      test: curl --fail http://localhost:8080 || exit 1
  api:
    image: ghcr.io/dodona-edu/dolos-api
    build: ./api/
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails db:prepare && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - dolos-api-storage:/dolos/storage
      - /tmp:/tmp
    environment:
      DOLOS_API_FRONT_END_URL: https://{INSERT DOLOS URL HERE}
      DOLOS_API_HOSTS: {INSERT DOLOS URL HERE}
      DOLOS_API_DISABLE_FORCE_SSL: false
      DOLOS_API_DATABASE_USERNAME: root
      DOLOS_API_DATABASE_PASSWORD: {INSERT PASSWORD HERE}
      DOLOS_API_DATABASE_HOST: db
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: true
      SECRET_KEY_BASE_DUMMY: true
    depends_on:
      db:
        condition: service_healthy
    networks:
      - dolos
        #    healthcheck:
        #      start_period: 2s
        #      interval: 10s
        #      test: curl --fail http://localhost:3000/up || exit 1
  worker:
    image: ghcr.io/dodona-edu/dolos-api
    build: ./api/
    command: bash -c "bundle exec rails jobs:work"
    volumes:
      - dolos-api-storage:/dolos/storage
      - /tmp:/tmp
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DOLOS_API_FRONT_END_URL: https://{INSERT DOLOS URL HERE}
      DOLOS_API_HOSTS: {INSERT DOLOS URL HERE}
      DOLOS_API_DATABASE_USERNAME: root
      DOLOS_API_DATABASE_PASSWORD:{INSERT PASSWORD HERE}
      DOLOS_API_DATABASE_HOST: db
      RAILS_ENV: production
      SECRET_KEY_BASE_DUMMY: true
      RAILS_LOG_TO_STDOUT: true
    depends_on:
      - api
    networks:
      - dolos
    healthcheck:
      start_period: 2s
      interval: 5s
      test: ruby -e true || exit 1
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./fullchain.pem:/etc/ssl/private/fullchain.pem
      - ./privkey.pem:/etc/ssl/private/privkey.pem
    ports:
      - "443:443"
      - "80:80"
    restart: always
    networks:
      - dolos
    depends_on:
      - api
      - web

volumes:
  dolos-db-data:
  dolos-api-storage:

networks:
  dolos:
```
